let str = "The child walked to the market";
let result = str.charAt(0).toUpperCase() + str.slice(1);
console.log(result);
let string = "example";
let updatedStr = string.slice(0, 3) + "X" + string.slice(3);
console.log(updatedStr);
let greeting = "hello world, hello JavaScript!";
let count = (greeting.match(/hello/g) || []).length;
console.log(count);
let lang = "JavaScript";
let lastThree = lang.slice(-3);
console.log(lastThree);
let text = "JavaScript";
let firstThree = text.slice(0, 3);
console.log(firstThree);
text = "JavaScript";
let sortedStr = text.split('').sort().join('');
console.log(sortedStr);
let message = "The child walked to the market";
let noSpaces = message.replace(/\s+/g, '');
console.log(noSpaces);
let greet = "greeting";
let index = greet.indexOf("t");
console.log(index);
str = "JavaScript";
let newStr = str.slice(2);
console.log(newStr);
 str = "JavaScript";
let updated = str.slice(0, -2);
console.log(updated);